modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
issueTrackerURL="https://github.com/Noach05/MissysDelight/issues" #optional

[[mods]] #mandatory
modId="missy" #mandatory
version="0.1B" #mandatory
displayName="Missy's Delight" #mandatory
#updateJSONURL="/" #optional
displayURL="" #optional
logoFile="logo.png" #optional
credits="CommandrMoose, _ILikePandas_, Jaycoby, TheArkNoah05, SpectrumFATM" #optional
authors="Original Author: CommandrMoose. New author: TheArkNoah05" #optional
description='''
Missy's Delight is an addon mod for the New TARDIS Mod, and a continuation of the original: The Master's Delight.'''


[[dependencies.missy]]
    modId="tardis"
    mandatory=true
    versionRange="[1.4,)"
    ordering="AFTER"
    side="BOTH"